\** MMFS ROM by Martin Mather
\** Compiled using BeebAsm V1.04
\** August 2011

\** OS CONSTANTS

PagedRomSelector_RAMCopy=&F4
PagedROM_PrivWorkspaces=&0DF0

EscapeFlag=&FF
TextPointer=&F2
ARGSV=&0214
FSCV=&021E

OSRDRM=&FFB9
GSINIT=&FFC2
GSREAD=&FFC5
OSFIND=&FFCE
OSGBPB=&FFD1
OSBPUT=&FFD4
OSBGET=&FFD7
OSARGS=&FFDA
OSFILE=&FFDD
OSBYTE=&FFF4
OSRDCH=&FFE0
OSASCI=&FFE3
OSNEWL=&FFE7
OSWRCH=&FFEE
OSWORD=&FFF1
OSCLI=&FFF7

TubeCode=&0406
TUBE_R1_STATUS=&FEE0
TUBE_R1_DATA=&FEE1
TUBE_R2_STATUS=&FEE2
TUBE_R2_DATA=&FEE3
TUBE_R3_STATUS=&FEE4
TUBE_R3_DATA=&FEE5
TUBE_R4_STATUS=&FEE6
TUBE_R4_DATA=&FEE7
